---

- hosts: master
  gather_facts: yes
  become: yes

  vars:
    # version needed by more than one role (namespace labels)
    istio_ingress_tested_from_localhost: true

  roles:
    #- role: istio-gateway

    # put TLS secret into 'istio-system' namespace also
    - { role: apply-k8s-tls-secrets, secret_namespace_list: [ 'default','istio-system'] }

