
# https://metallb.universe.tf/configuration/migration_to_crds/
# v0.11.0 is latest version of MetalLB that still supports ConfigMap 
#metallb_version: v0.11.0

# for newer K8s clusters that have deprected PodSecurityPolicy
# requires newer CRD style configuration with IPAddressPool (not ConfigMap)
metallb_version: v0.13.9
