---

- name: check kubectl
  become: yes
  command: kubectl get nodes
  register: getnodes
- debug: msg="{{getnodes.stdout_lines}}"

- name: create file out of every jinja2 templates
  template:
    src: "{{item}}"
    dest: "./{{ item | basename | regex_replace('.j2$', '') }}"
  with_fileglob: "../templates/*.j2"

- name: apply nginx ingress to golang-hello-world-web
  shell: kubectl apply -f ./golang-hello-world-web-on-nginx.yaml
  become: yes
  register: stdout
- debug: msg="{{stdout.stdout_lines}}"

- name: apply deployment for second ingress
  block:
    - name: apply nginx ingress to golang-hello-world-web2
      shell: kubectl apply -f ./golang-hello-world-web-on-nginx2.yaml
      become: yes
  when: do_second_ingress
